### ISSUE TITLE
[Bug] Ligolo is incompatible with wintun 0.14

### ISSUE THREAD

**Issue by itsTurnip** [tnpitsecurity/ligolo-ng#8]
Hi!

I was testing out your tool and there is issue in using it with wintun v0.14.1 (but works fine with wintun 0.13). [Here ](https://www.toptal.com/developers/hastebin/urocabaluh.go) you can check log output.

Thanks for your work!

**Comment by Nicocha30** [comment]
Can you send the log output over GitHub?

Thanks!

**Comment by itsTurnip** [comment]
Here it is:

```
.\proxy.exe -selfcert
unexpected fault address 0xffffffffffffffff
fatal error: fault
[signal 0xc0000005 code=0x0 addr=0xffffffffffffffff pc=0x4deb3d]

goroutine 1 [running, locked to thread]:
runtime.throw({0x93b587, 0xc0000ab550})
        /opt/hostedtoolcache/go/1.17.1/x64/src/runtime/panic.go:1198 +0x76 fp=0xc0000ca8b8 sp=0xc0000ca888 pc=0x396936
runtime.sigpanic()
        /opt/hostedtoolcache/go/1.17.1/x64/src/runtime/signal_windows.go:260 +0x10c fp=0xc0000ca900 sp=0xc0000ca8b8 pc=0x3a982c
golang.org/x/sys/windows.UTF16PtrToString(0xc0000ab5d8)
        /home/runner/go/pkg/mod/golang.org/x/sys@v0.0.0-20210630005230-0f9fa26af87c/windows/syscall_windows.go:132 +0x1d fp=0xc0000ca948 sp=0xc0000ca900 pc=0x4deb3d
golang.zx2c4.com/wireguard/tun/wintun.setupLogger.func1(0xc0000ab620, 0xc0000ab628)
        /home/runner/go/pkg/mod/golang.zx2c4.com/wireguard@v0.0.0-20210905140043-2ef39d47540c/tun/wintun/wintun_windows.go:53 +0x1c fp=0xc0000ca990 sp=0xc0000ca948 pc=0x819fbc
runtime.call16(0x0, 0x9674a0, 0xc0000caa18, 0x0, 0x0, 0x10, 0xc0000cac70)
        /opt/hostedtoolcache/go/1.17.1/x64/src/runtime/asm_amd64.s:625 +0x50 fp=0xc0000ca9b0 sp=0xc0000ca990 pc=0x3c2630
runtime.callbackWrap(0x40169feef0)
        /opt/hostedtoolcache/go/1.17.1/x64/src/runtime/syscall_windows.go:378 +0x134 fp=0xc0000cad90 sp=0xc0000ca9b0 pc=0x3b1af4
runtime.cgocallbackg1(0x3b19c0, 0xdf8140, 0x0)
        /opt/hostedtoolcache/go/1.17.1/x64/src/runtime/cgocall.go:306 +0x29a fp=0xc0000cae60 sp=0xc0000cad90 pc=0x3644ba
runtime.cgocallbackg(0xc00004a000, 0x300000002, 0xc00004a000)
        /opt/hostedtoolcache/go/1.17.1/x64/src/runtime/cgocall.go:232 +0x106 fp=0xc0000caef8 sp=0xc0000cae60 pc=0x364146
runtime.cgocallbackg(0x3b19c0, 0x40169feef0, 0x0)
        <autogenerated>:1 +0x36 fp=0xc0000caf20 sp=0xc0000caef8 pc=0x3c63f6
runtime.cgocallback(0x363fcc, 0x3c5d00, 0xdf8420)
        /opt/hostedtoolcache/go/1.17.1/x64/src/runtime/asm_amd64.s:915 +0xd7 fp=0xc0000caf48 sp=0xc0000caf20 pc=0x3c4237
runtime.systemstack_switch()
        /opt/hostedtoolcache/go/1.17.1/x64/src/runtime/asm_amd64.s:350 fp=0xc0000caf50 sp=0xc0000caf48 pc=0x3c20e0
runtime.cgocall(0x3c5d00, 0xdf8420)
        /opt/hostedtoolcache/go/1.17.1/x64/src/runtime/cgocall.go:166 +0xac fp=0xc0000caf88 sp=0xc0000caf50 pc=0x363fcc
syscall.Syscall(0x7ffa0f8a3a80, 0x2, 0xc000156000, 0xc0000ab7e0, 0x0)
        /opt/hostedtoolcache/go/1.17.1/x64/src/runtime/syscall_windows.go:479 +0xf4 fp=0xc0000cafc0 sp=0xc0000caf88 pc=0x3c0934
syscall.Syscall(0xc000103920, 0x40, 0x0, 0xe0, 0x40)
        <autogenerated>:1 +0x2b fp=0xc0000cb010 sp=0xc0000cafc0 pc=0x3c6beb
golang.zx2c4.com/wireguard/tun/wintun.(*Pool).OpenAdapter(0xc000156000, {0x93ba31, 0x30})
        /home/runner/go/pkg/mod/golang.zx2c4.com/wireguard@v0.0.0-20210905140043-2ef39d47540c/tun/wintun/wintun_windows.go:89 +0xbc fp=0xc0000cb088 sp=0xc0000cb010 pc=0x81985c
golang.zx2c4.com/wireguard/tun.CreateTUNWithRequestedGUID({0x93ba31, 0x6}, 0x36d427, 0x5dc)
        /home/runner/go/pkg/mod/golang.zx2c4.com/wireguard@v0.0.0-20210905140043-2ef39d47540c/tun/tun_windows.go:75 +0x4d fp=0xc0000cb100 sp=0xc0000cb088 pc=0x81ac2d
golang.zx2c4.com/wireguard/tun.CreateTUN(...)
        /home/runner/go/pkg/mod/golang.zx2c4.com/wireguard@v0.0.0-20210905140043-2ef39d47540c/tun/tun_windows.go:63
ligolo-ng/pkg/proxy/netstack/tun.Open({0x93ba31, 0x0})
        /home/runner/work/ligolo-ng/ligolo-ng/pkg/proxy/netstack/tun/wireguard.go:11 +0x2e fp=0xc0000cb140 sp=0xc0000cb100 pc=0x81c0ce
ligolo-ng/pkg/proxy/netstack.(*NetStack).new(0xc000096798, {0x93ba31, 0x6})
        /home/runner/work/ligolo-ng/ligolo-ng/pkg/proxy/netstack/stack.go:174 +0x3ca fp=0xc0000cbd50 sp=0xc0000cb140 pc=0x81f62a
ligolo-ng/pkg/proxy/netstack.NewStack(...)
        /home/runner/work/ligolo-ng/ligolo-ng/pkg/proxy/netstack/stack.go:87
ligolo-ng/cmd/proxy/app.Run({0x93ba31, 0x6})
        /home/runner/work/ligolo-ng/ligolo-ng/cmd/proxy/app/app.go:55 +0xd2 fp=0xc0000cbdf8 sp=0xc0000cbd50 pc=0x820752
main.main()
        /home/runner/work/ligolo-ng/ligolo-ng/cmd/proxy/main.go:38 +0x2a6 fp=0xc0000cbf80 sp=0xc0000cbdf8 pc=0x8244c6
runtime.main()
        /opt/hostedtoolcache/go/1.17.1/x64/src/runtime/proc.go:255 +0x217 fp=0xc0000cbfe0 sp=0xc0000cbf80 pc=0x398ef7
runtime.goexit()
        /opt/hostedtoolcache/go/1.17.1/x64/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0000cbfe8 sp=0xc0000cbfe0 pc=0x3c4461

goroutine 19 [select]:
gvisor.dev/gvisor/pkg/sync.Gopark(...)
        /home/runner/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210923032606-0801d469950e/pkg/sync/runtime_unsafe.go:32
gvisor.dev/gvisor/pkg/sleep.(*Sleeper).nextWaker(0xc000174018, 0x1)
        /home/runner/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210923032606-0801d469950e/pkg/sleep/sleep_unsafe.go:181 +0x79
gvisor.dev/gvisor/pkg/sleep.(*Sleeper).Fetch(0x0, 0x0)
        /home/runner/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210923032606-0801d469950e/pkg/sleep/sleep_unsafe.go:228 +0x2e
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*processor).start(0xc000174000, 0x0)
        /home/runner/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210923032606-0801d469950e/pkg/tcpip/transport/tcp/dispatcher.go:97 +0x94
created by gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*dispatcher).init
        /home/runner/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210923032606-0801d469950e/pkg/tcpip/transport/tcp/dispatcher.go:163 +0xb3

goroutine 20 [select]:
gvisor.dev/gvisor/pkg/sync.Gopark(...)
        /home/runner/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210923032606-0801d469950e/pkg/sync/runtime_unsafe.go:32
gvisor.dev/gvisor/pkg/sleep.(*Sleeper).nextWaker(0xc000174090, 0x1)
        /home/runner/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210923032606-0801d469950e/pkg/sleep/sleep_unsafe.go:181 +0x79
gvisor.dev/gvisor/pkg/sleep.(*Sleeper).Fetch(0x0, 0x0)
        /home/runner/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210923032606-0801d469950e/pkg/sleep/sleep_unsafe.go:228 +0x2e
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*processor).start(0xc000174078, 0x0)
        /home/runner/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210923032606-0801d469950e/pkg/tcpip/transport/tcp/dispatcher.go:97 +0x94
created by gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*dispatcher).init
        /home/runner/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210923032606-0801d469950e/pkg/tcpip/transport/tcp/dispatcher.go:163 +0xb3

goroutine 21 [select]:
gvisor.dev/gvisor/pkg/sync.Gopark(...)
        /home/runner/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210923032606-0801d469950e/pkg/sync/runtime_unsafe.go:32
gvisor.dev/gvisor/pkg/sleep.(*Sleeper).nextWaker(0xc000174108, 0x1)
        /home/runner/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210923032606-0801d469950e/pkg/sleep/sleep_unsafe.go:181 +0x79
gvisor.dev/gvisor/pkg/sleep.(*Sleeper).Fetch(0x0, 0x0)
        /home/runner/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210923032606-0801d469950e/pkg/sleep/sleep_unsafe.go:228 +0x2e
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*processor).start(0xc0001740f0, 0x0)
        /home/runner/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210923032606-0801d469950e/pkg/tcpip/transport/tcp/dispatcher.go:97 +0x94
created by gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*dispatcher).init
        /home/runner/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210923032606-0801d469950e/pkg/tcpip/transport/tcp/dispatcher.go:163 +0xb3

goroutine 22 [select]:
gvisor.dev/gvisor/pkg/sync.Gopark(...)
        /home/runner/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210923032606-0801d469950e/pkg/sync/runtime_unsafe.go:32
gvisor.dev/gvisor/pkg/sleep.(*Sleeper).nextWaker(0xc000174180, 0x1)
        /home/runner/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210923032606-0801d469950e/pkg/sleep/sleep_unsafe.go:181 +0x79
gvisor.dev/gvisor/pkg/sleep.(*Sleeper).Fetch(0x0, 0x0)
        /home/runner/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210923032606-0801d469950e/pkg/sleep/sleep_unsafe.go:228 +0x2e
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*processor).start(0xc000174168, 0x0)
        /home/runner/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210923032606-0801d469950e/pkg/tcpip/transport/tcp/dispatcher.go:97 +0x94
created by gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*dispatcher).init
        /home/runner/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20210923032606-0801d469950e/pkg/tcpip/transport/tcp/dispatcher.go:163 +0xb3
```

**Comment by Nicocha30** [comment]
Should be fixed in https://github.com/tnpitsecurity/ligolo-ng/commit/091996f6c951d925e093c4cfa30e065b1d8ff10f (v0.3) !
